USE QLVT
--CAU 1
SELECT *
FROM VATTU
WHERE TENVT LIKE '%a%';
-- CAU 2
SELECT DONDH.SODH, DONDH.NGAYDAT, SUM(CTDONDH.SOLUONG * VATTU.DONGIA) AS TONGTIEN
FROM DONDH JOIN CTDONDH ON DONDH.SODH = CTDONDH.SODH
JOIN VATTU ON CTDONDH.MAVT = VATTU.MAVT
WHERE MONTH(DONDH.NGAYDAT) BETWEEN '4' AND '6' AND  YEAR(DONDH.NGAYDAT) = '2023'
GROUP BY DONDH.SODH, DONDH.NGAYDAT

-- CAU 3
SELECT *
FROM VATTU
WHERE SLTON = (SELECT MAX(SLTON) FROM VATTU)
-- CAU 4
SELECT VATTU.MAVT, VATTU.TENVT
FROM VATTU JOIN CTDONDH ON CTDONDH.MAVT = VATTU.MAVT
JOIN DONDH ON DONDH.SODH = CTDONDH.SODH
WHERE DONDH.MANCC = 'NHACC01' AND DONDH.NGAYGIAO = '4/21/2023'

-- CAU 5
SELECT TOP 3 VATTU.TENVT, VATTU.MAVT, COUNT(*) AS TONGSOLUONG
FROM VATTU JOIN CTDONDH ON CTDONDH.MAVT = VATTU.MAVT
JOIN DONDH ON DONDH.SODH = CTDONDH.SODH
WHERE YEAR(DONDH.NGAYDAT) = ' 2023 '
GROUP BY VATTU.TENVT, VATTU.MAVT
ORDER BY TONGSOLUONG DESC

-- CAU 6
SELECT VATTU.MAVT, VATTU.TENVT, VATTU.DVTINH, CTDONDH.SOLUONG, VATTU.DONGIA, (CTDONDH.SOLUONG * VATTU.DONGIA) AS TRIGIA
FROM VATTU JOIN CTDONDH ON CTDONDH.MAVT = VATTU.MAVT
WHERE  SODH = 'DH01' AND (CTDONDH.SOLUONG * VATTU.DONGIA) > 100000;

-- CAU 7
SELECT NHACC.MANCC, NHACC.TENNCC, DONDH.SODH, DONDH.NGAYDAT, DONDH.NGAYGIAO, SUM(VATTU.DONGIA * CTDONDH.SOLUONG) AS TONGTIEN
FROM NHACC JOIN DONDH ON NHACC.MANCC = DONDH.MANCC
JOIN CTDONDH ON CTDONDH.SODH = DONDH.SODH
JOIN VATTU ON VATTU.MAVT = CTDONDH.MAVT
GROUP BY NHACC.MANCC, NHACC.TENNCC, DONDH.SODH, DONDH.NGAYDAT, DONDH.NGAYGIAO
HAVING SUM(VATTU.DONGIA * CTDONDH.SOLUONG) >= ALL(SELECT SUM(VATTU.DONGIA * CTDONDH.SOLUONG) FROM VATTU JOIN CTDONDH ON CTDONDH.MAVT = VATTU.MAVT GROUP BY CTDONDH.SODH)

-- CAU 8
SELECT *
FROM VATTU
WHERE DONGIA IN (SELECT DONGIA FROM VATTU GROUP BY DONGIA HAVING COUNT(*) > 1)

-- CAU 9
SELECT NHACC.MANCC, NHACC.TENNCC
FROM NHACC JOIN DONDH ON DONDH.MANCC = NHACC.MANCC
WHERE DONDH.SODH IN (SELECT SODH FROM CTDONDH GROUP BY SODH HAVING COUNT(*) = (SELECT COUNT(*) FROM VATTU))

-- CAU 10
SELECT VATTU.MAVT, VATTU.TENVT
FROM VATTU JOIN CTDONDH ON VATTU.MAVT = CTDONDH.MAVT
JOIN DONDH ON DONDH.SODH = CTDONDH.SODH
WHERE DONDH.NGAYDAT != '2023'
GROUP BY VATTU.MAVT, VATTU.TENVT
USE QLVT
INSERT INTO VATTU VALUES('VT01', 'SAT', 'KG', 20000, 12);
INSERT INTO VATTU VALUES('VT02', 'DONG', 'KG', 50000, 20);
INSERT INTO VATTU VALUES('VT03', 'THEP', 'KG', 100000, 17);
INSERT INTO VATTU VALUES('VT04', 'NHOM', 'KG', 10000, 15);
INSERT INTO VATTU VALUES('VT05', 'KEM', 'KG', 30000, 9);
INSERT INTO VATTU VALUES('VT06', 'CHI', 'KG', 30000, 9);

INSERT INTO NHACC VALUES('NHACC01', 'TON HOA SEN', 'TPHCM', '034781');
INSERT INTO NHACC VALUES('NHACC02', 'THANH PHAT', 'TPHCM', '034781');
INSERT INTO NHACC VALUES('NHACC03', 'VINGROUP', 'TPHCM', '034781');
INSERT INTO NHACC VALUES('NHACC04', 'MELIDIO', 'TPHCM', '034781');
INSERT INTO NHACC VALUES('NHACC05', 'THEP TON HOA', 'TPHCM', '034781');

INSERT INTO DONDH VALUES('DH01', '4/20/2023', '4/21/2023', 'NHACC01');
INSERT INTO DONDH VALUES('DH02', '4/27/2023', '4/30/2023', 'NHACC02');
INSERT INTO DONDH VALUES('DH03', '6/19/2023', '6/21/2023', 'NHACC03');
INSERT INTO DONDH VALUES('DH04', '12/9/2023', '12/13/2023', 'NHACC04');
INSERT INTO DONDH VALUES('DH05', '4/6/2023', '4/8/2023', 'NHACC05');


INSERT INTO CTDONDH VALUES('DH01','VT01', 23);
INSERT INTO CTDONDH VALUES('DH01','VT02', 24);
INSERT INTO CTDONDH VALUES('DH01','VT03', 20);
INSERT INTO CTDONDH VALUES('DH01','VT04', 10);
INSERT INTO CTDONDH VALUES('DH01','VT05', 19);
INSERT INTO CTDONDH VALUES('DH01','VT06', 19);

INSERT INTO CTDONDH VALUES('DH02','VT03', 23);
INSERT INTO CTDONDH VALUES('DH03','VT05', 3);
INSERT INTO CTDONDH VALUES('DH04','VT04', 30);
INSERT INTO CTDONDH VALUES('DH05','VT01', 23);